import { GeistSans } from "geist/font/sans";
import type { Metadata } from "next";
import Navbar from "./components/Navbar";
import "./globals.css";

export const metadata: Metadata = {
  title: "OhiSiam - Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${GeistSans.className}`}>
        <div className="container md:max-w-3xl lg:max-w-5xl">
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
